currentsystem:
  version: 01.02.07

# 服务配置
server:
  max-http-header-size: 10240
  tomcat:
    relaxed-path-chars: '<,>,[,\,],^,`,{,|,}'
    relaxed-query-chars: '<,>,[,\,],^,`,{,|,}'

# spring相关配置
spring:
  profiles:
    active: @spring.active@
  servlet:
    multipart:
      #文件最大上传大小配置 最大上传100M
      max-request-size: 100MB
      #文件最大上传大小配置 最大上传100M
      max-file-size: 100MB
  jackson:
    time-zone: GMT+8
    #date-format: yyyy-MM-dd HH:mm:ss.SSS
    date-format: yyyy-MM-dd HH:mm:ss # 20210318-1236，去掉“.SSS”！
    locale: zh_CN
    serialization:
      INDENT_OUTPUT: false
    default-property-inclusion: non_null # 20210427：JSON不显示值为null的字段！
  devtools:
    restart:
      enabled: false # 设置关闭热部署：这里关闭，但是下面 freemarker.cache: false，可以使得静态页面实现热部署，但是动态代码不热部署！
  freemarker:
    cache: false # 页面不加载缓存，修改即时生效

# mybaits相关配置
mybatis-plus:
  mapper-locations: classpath*:com/cn/**/mapping/*.xml, classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
      table-underline: true
    enable-sql-runner: true
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
